name: Setup Terraform Workspace
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  setup_workspace:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_NAME: "PR-${{ github.event.number }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Create AWS credentials directory
        run: mkdir -p ~/.aws
        
      - name: Configure AWS credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Update Terraform Configuration
        run: |
          WORKSPACE_NAME="PR-${{ github.event.number }}"
      
      - name: list files
        run: |
              ls -ltr
              echo "Using WORKSPACE_NAME: $WORKSPACE_NAME"

      - name: Initialize Terraform
        run: |
             cd terraform-base
             terraform init                                    #-backend=false

      - name: Create Terraform Workspace
        run: |
             cd terraform-base
             terraform workspace new $WORKSPACE_NAME || terraform workspace select $WORKSPACE_NAME

      - name: Initialize Terraform
        run: |
           cd terraform-base
           terraform init
           
      - name: plan terraform
        run: |
           cd terraform-base
           terraform plan

      - name: list workspaces
        run:  terraform workspace list

      - name: terraform apply
        run: |
            cd terraform-base
            terraform destroy --auto-approve